/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rub_nds_research_timingsocket_TimingSocketImpl_TimingInputStream */

#ifndef _Included_de_rub_nds_research_timingsocket_TimingSocketImpl_TimingInputStream
#define _Included_de_rub_nds_research_timingsocket_TimingSocketImpl_TimingInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef de_rub_nds_research_timingsocket_TimingSocketImpl_TimingInputStream_MAX_SKIP_BUFFER_SIZE
#define de_rub_nds_research_timingsocket_TimingSocketImpl_TimingInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
