/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rub_nds_research_timingsocket_TimingSocketImpl_TimingOutputStream */

#ifndef _Included_de_rub_nds_research_timingsocket_TimingSocketImpl_TimingOutputStream
#define _Included_de_rub_nds_research_timingsocket_TimingSocketImpl_TimingOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
